application: mywaveid
version: newlive
runtime: python
api_version: 1

handlers:
- url: /_wave/.*
  script: mywaveid.py
- url: /assets
  static_dir: assets 
- url: /favicon.ico
  static_files: assets/favicon.ico
  upload: assets/favicon.ico
- url: /icon.gif
  static_files: assets/icon.gif
  upload: assets/icon.gif
- url: /icon.png
  static_files: assets/icon.png
  upload: assets/icon.png
- url: /.*
  static_files: static/html/index.html
  upload: static/html/index.html
  